Repository Prescrypto/prescrypto-docs, pull requests merged in 2022-02, with the labels that each got.

#14 Some clarity changes and updated README
  .github/workflows/deploy.yml
  .github/workflows/test-deploy.yml
  README.md
  docusaurus.config.js
Labels: documentation

#20 update docs and changelog
  docs/api/medic.md
  docs/changelog/overview.md
  docs/tutorial/overview.md
Labels: Done, QA Done

#22 make a ignore file on documentation
  docs/api/_medication.md
Labels: Done
